# Generated by Django 4.2.11 on 2024-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookAuthor',
            new_name='BookAuthors',
        ),
        migrations.AlterModelTable(
            name='author',
            table='books_author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books_book',
        ),
        migrations.AlterModelTable(
            name='bookauthors',
            table='books_book_authors',
        ),
        migrations.AlterModelTable(
            name='bookbookshelves',
            table='books_book_bookshelves',
        ),
        migrations.AlterModelTable(
            name='booklanguages',
            table='books_book_languages',
        ),
        migrations.AlterModelTable(
            name='bookshelf',
            table='books_bookshelf',
        ),
        migrations.AlterModelTable(
            name='booksubjects',
            table='books_book_subjects',
        ),
        migrations.AlterModelTable(
            name='format',
            table='books_format',
        ),
        migrations.AlterModelTable(
            name='language',
            table='books_language',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='books_subject',
        ),
    ]
